package Exception.Q1;

public class Q1 {

    public static void main(String[] args) {
        // Using try-catch block
//        try{
//            System.out.println(67/0);
//        }
//        catch(ArithmeticException ae){
//            System.out.println("Divide by zero exception !!");
//        }

        // Without using try-catch block
//        System.out.println(67/0);

    }
}
